# Generated by Django 3.2.4 on 2021-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_alter_stork_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('market', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('eng_name', models.CharField(max_length=50)),
            ],
        ),
    ]

